<?php
include 'session.php';
include 'connection.php';
?>

<!DOCTYPE html>
<html lang="en" class="light">
<!-- BEGIN: Head -->
<head>
    <meta charset="utf-8">
    <link href="dist/images/logo.svg" rel="shortcut icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="About Us - Art Gallery">
    <title>About Us - Art Gallery</title>
    <link rel="stylesheet" href="dist/css/app.css" />
</head>
<!-- END: Head -->

<body class="py-5 md:py-0 bg-white">
    <!-- BEGIN: Mobile Menu -->
    <div class="mobile-menu md:hidden">
        <div class="mobile-menu-bar">
            <a href="" class="flex mr-auto">
                <img alt="Midone - HTML Admin Template" class="w-6" src="dist/images/logo.svg">
            </a>
            <a href="javascript:;" class="mobile-menu-toggler"> <i data-lucide="bar-chart-2" class="w-8 h-8 text-white transform -rotate-90"></i> </a>
        </div>
        <div class="scrollable">
            <a href="javascript:;" class="mobile-menu-toggler"> <i data-lucide="x-circle" class="w-8 h-8 text-white transform -rotate-90"></i> </a>
            <ul class="scrollable__content py-2">
                <!-- Mobile menu content is generated by the template; keep items minimal -->
                <li>
                    <a href="dashboard.php" class="menu">
                        <div class="menu__icon"> <i data-lucide="home"></i> </div>
                        <div class="menu__title"> Dashboard </div>
                    </a>
                </li>
                <li>
                    <a href="about.php" class="menu">
                        <div class="menu__icon"> <i data-lucide="info"></i> </div>
                        <div class="menu__title"> About </div>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="flex mt-[4.7rem] md:mt-0 overflow-hidden">
    <!-- BEGIN: Side Menu -->
    <?php include 'sideMenu.php' ?>
    <!-- END: Side Menu -->

    <!-- BEGIN: Content -->
    <div class="content">
        <!-- BEGIN: Top Bar -->
        <?php include 'topBar.php' ?>
        <!-- END: Top Bar -->

        <div class="intro-y flex items-center mt-8">
            <h2 class="text-lg font-medium mr-auto">About Us</h2>
        </div>

        <div class="grid grid-cols-12 gap-6 mt-5">
            <div class="intro-y col-span-12 lg:col-span-12">
                <div class="intro-y box p-6">
                    <!-- Painting hero image -->
                    <div class="mb-6 text-center">
                        <img src="https://i.pinimg.com/1200x/f6/44/a4/f644a441ae6fbd0aae40c183a1407ef8.jpg" alt="Painting" class="mx-auto mb-6 w-full sm:w-3/4 lg:w-1/2 rounded shadow-sm">
                    </div>
                    <h3 class="text-xl font-semibold mb-4">Who we are</h3>
                    <p class="text-slate-600">Art Gallery is an e-commerce management dashboard built to showcase and manage artworks, categories and purchases. We combine a modern UI with a lightweight PHP backend to help artists and gallery owners manage their collections and sales.</p>

                    <hr class="my-6">

                    <h3 class="text-xl font-semibold mb-4">Our mission</h3>
                    <p class="text-slate-600">To empower creators and small galleries with an intuitive admin interface so they can focus on creating and selling artwork — not wrestling with complicated tools.</p>

                    <hr class="my-6">

                    

                    <hr class="my-6">

                    
            </div>
        </div>

    </div>
    <!-- END: Content -->
</div>

<script src="dist/js/app.js"></script>
</body>
</html>
